### ISSUE TITLE
input 9000 tweets but return only 7000 results

### ISSUE THREAD

**Issue by xiaoleihuang** [ianozsvald/ark-tweet-nlp-python#7]
I modified your wrapper code to make it more compatible with python 3(because of utf8). 
But when I used its function runtagger_parse(), but I got wrong number of results here: input with 9000 but only got 7000...I guess it might be wrong in _split_results() or elsewhere....

The attached file is the py file....

[CMUTweetTagger (copy).txt](https://github.com/ianozsvald/ark-tweet-nlp-python/files/501830/CMUTweetTagger.copy.txt)

**Comment by ianozsvald** [comment]
Hey there. So, I'm not supporting this any more, I've not touched it in 4 years. If you wanted to support a more-live version I'd be happy to update my README to point at your repo. If not, I'll just edit my README to note that I'm not supporting it. Cheers, Ian.

**Comment by xiaoleihuang** [comment]
Hi, @ianozsvald , Got it. Yeah, after analysis, there are some problems when the wrapper tried to parse the many (for my case over 9000 samples) stdout from java. I tried to write my own wrapper that parses one tweet per time. However, I found each time python just invoked a new java jvm for running once, it was way too time consuming. So, I am trying to create a java restful service and keep the java parser in memory to solve such a problem. Any good restful comments from you would be welcomed, because I am new in restful services. I will post my new progresses...

**Comment by xiaoleihuang** [comment]
Hi, @ianozsvald 
I find another better gateway connects java and python: py4j. Not only, it is very easy to be used & deployed, but also it is updated & maintained regularly. I will attach a link here after I finish it.

**Comment by xiaoleihuang** [comment]
@ianozsvald 
https://github.com/xiaoleihuang/CMUTwitterWrapper
This is my initial push here. Write in hurry. Due to my homework's deadline, more modification will be made in the future. The code can run faster than yours...It does not need any split or further process. Wrapped in a list of java Pairs... Any comments will be welcomed.
